### ISSUE TITLE
Failed to read Error when running main.py

### ISSUE THREAD

**Issue by ghost** [zdhNarsil/GFlowNet-CombOpt#1]
Hi, I generated a dataset then tried to run main.py and am getting Failed to read errors followed by the paths of the graphs. I verified the paths specified exist and point to graph .gpickle files.

How might I resolve this issue?

**Comment by zdhNarsil** [comment]
Hi, I wonder if you could provide more specific description? (like what is the error message and how you generate the data)

**Comment by ghost** [comment]
After following the instructions in README.md I get many of this error after executing main.py
`Failed to read /GFlowNet-CombOpt/data/rb200-300/train/GR_200_300_2085.gpickle.`

followed by this

`Error executing job with overrides: ['input=rb200-300', 'alg=fl', 'bsit=8']
Traceback (most recent call last):
  File "/GFlowNet-CombOpt/gflownet/main.py", line 150, in main
    train_loader, test_loader = get_data_loaders(cfg)
  File "/GFlowNet-CombOpt/gflownet/data.py", line 106, in get_data_loaders
    train_loader = DataLoader(trainset, batch_size=train_batch_size,
  File ".conda/envs/flow4/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/.conda/envs/flow4/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

**Comment by Oliver-0423** [comment]
same issue

**Comment by zdhNarsil** [comment]
I hav not encountered this. Can you try re-generate the data files?

**Comment by HanbumKo** [comment]
I have solved with specific networkx version
`pip install networkx==2.5.0`

**Comment by zdhNarsil** [comment]
Closing this issue as it is due to version mismatch.
