### ISSUE TITLE
about BA and SATLIB

### ISSUE THREAD

**Issue by pjy0422** [zdhNarsil/GFlowNet-CombOpt#2]
Hi, I would like to reproduce your experiment.
I was able to reproduce the MIS and MC results in rb graph.
In MDS, MCut, ba graph and SATLIB are not included in the code?
How should I get the data?
Thank you.

**Comment by zdhNarsil** [comment]
Hi,
This repo might be helpful to you:
https://github.com/MaxiBoether/mis-benchmark-framework

**Comment by pjy0422** [comment]
thank you!
